arb_shading_language_420pack: Fix test with NVIDIA drivers
following error is output instead of the expected linker error:
    Failed to compile VS: 0(4) : error C0000: syntax error, unexpected '(', expecting "::" at token "("
    0(11) : warning C7533: global variable gl_Vertex is deprecated after version 120

with NVIDIA drivers on Linux:
OpenGL version string: 4.6.0 NVIDIA 390.116
OpenGL shading language version string: 4.60 NVIDIA